### ISSUE TITLE
GMNotes breaks new character sheet header in dnd5e 3.0.2 with label enabled

### ISSUE THREAD

**Issue by illandhil** [bithir/gm-notes#34]
After upgrading to dnd5e 3.0.2 (worked fine it 3.0.1) GMNotes breaks the player character sheet header if GMNotes Label is enabled in the settings. If I turn off the Label setting its a little wonky with CSS but the rest of the character sheet header (X, Select Sheet, etc) work.

**Comment by neovatar** [comment]
Same for me, can confirm.

**Comment by bithir** [comment]
Not sure what they've done.
Quick workaround - go to settings for GM note and configure it to hide the label.
That looks like it corrects it for me
![image](https://github.com/bithir/gm-notes/assets/19734037/8bdb26e1-3413-48fa-9bc7-6685c4f20859)

Please confirm if it fixes it for you.  It looks like dnd5e now does something with the text layout that makes it expand greatly.

**Comment by bithir** [comment]
![image](https://github.com/bithir/gm-notes/assets/19734037/64c0e3d7-39ad-4424-86e3-a62e3c5e53a5)

I think that looks like it should - but as I do not use dnd5e, I will need some help with this, as I am not even sure how it should look when it looks correct :D

**Comment by bithir** [comment]
![image](https://github.com/bithir/gm-notes/assets/19734037/77199b03-6ef6-4d55-8dfd-650f7711193d)

Solved in release 9.0
