### ISSUE TITLE
Where is the Migration button?

### ISSUE THREAD

**Issue by Nedrapter** [bithir/gm-notes#43]
![image](https://github.com/user-attachments/assets/ffe2b1cc-15fa-49b0-8649-fe2fe475412e)

I saw the Chat message mentioning a migration button but I see none.
![image](https://github.com/user-attachments/assets/7bc46590-8fdc-4ff9-a94f-c92adcf7dfba)
Where should I be looking?

**Comment by JustAnotherIdea** [comment]
That's weird. Can you confirm you've updated the module? What version of foundry are you on?

**Comment by Nedrapter** [comment]
Oh I assumed that since the message showed, the module got updated, but apparently I hadn't updated yet. Strange the you get notifications for updates you haven't done :D

**Comment by bithir** [comment]
I'll make that clearer next time I push as message.

I've amended the message now to say 

> A new release is now available. The new release contains rework for journal handling allowing per-page notes and integration with Monks Enhanced Journal.  Some minor fixes for selection of text.  Big thanks to @JustAnotherIdea.  When you are on 10.0 of GM Notes remember to go to configuration and hit 'migrate' to migrate over existing journals.

Only someone who has not seen the message will be shown it.
