### ISSUE TITLE
What does this do?

### ISSUE THREAD

**Issue by Nedrapter** [bithir/gm-notes#44]
![image](https://github.com/user-attachments/assets/7a093753-fcf2-4763-a768-f7d8abbeecb3)
I see those 2 button above but I fail to understand what they do. When I click the left one, nothing happens. When I click the right one, the text gets deleted. I've looked a new journal (reading that the last update had something to do with Monk's EJ, but I see no journal. Checked the actor's biography tab, nothing there as well. Assuming it went somewhere that I could not find, I pressed the left option again, hoping to return back here, but nothing happened.

**Comment by JustAnotherIdea** [comment]
Right now for non journal objects, the whole description is moved to/from the gm notes. It's possible the new implementation does something weird with actor notes I didn't catch. I'll look into it this week

**Comment by bithir** [comment]
It is supposed to prefix it to the BIO section of the character in dnd5e and the journal. I do not use dnd5e, so it might be possible that dnd5e have moved the BIO section from where it is in the past (`system.details.biography.value`).  I've been tempted to remove this functionality for quite some time, because I think it adds very little value and the overhead to maintain the functionality feels a lot higher than it deserves.  I guess it was originally going to be a thing for more systems than dnd5e, but I do not think it is a particular required functionality and it is poorly understood what the use of it is.

**Comment by bithir** [comment]
Opened official issue #45 for it.

**Comment by Nedrapter** [comment]
> It is supposed to prefix it to the BIO section of the character in dnd5e and the journal. I do not use dnd5e, so it might be possible that dnd5e have moved the BIO section from where it is in the past (`system.details.biography.value`). I've been tempted to remove this functionality for quite some time, because I think it adds very little value and the overhead to maintain the functionality feels a lot higher than it deserves. I guess it was originally going to be a thing for more systems than dnd5e, but I do not think it is a particular required functionality and it is poorly understood what the use of it is.

In that case, what does the integration wth MEJ add?
(yes the Bio has been moved I think or redesigned since then for dnd5e)

**Comment by JustAnotherIdea** [comment]
> > It is supposed to prefix it to the BIO section of the character in dnd5e and the journal. I do not use dnd5e, so it might be possible that dnd5e have moved the BIO section from where it is in the past (`system.details.biography.value`). I've been tempted to remove this functionality for quite some time, because I think it adds very little value and the overhead to maintain the functionality feels a lot higher than it deserves. I guess it was originally going to be a thing for more systems than dnd5e, but I do not think it is a particular required functionality and it is poorly understood what the use of it is.
> 
> In that case, what does the integration wth MEJ add?
> (yes the Bio has been moved I think or redesigned since then for dnd5e)

The integration with MEJ just adds the GM notes and the GM notes button to the MEJ windows (note this is not optimized so the button may take a few seconds to show)

I will look into supporting dnd5e actor biographies
