### ISSUE TITLE
It doesnt works

### ISSUE THREAD

**Issue by HenrikSonntag** [bithir/gm-notes#8]
it no longer works with The dark eye.
Module is active but the GM Notes are no longer there.
the dark eye 4.3.7
Foundry version 10 build 291

**Comment by bithir** [comment]
Hmm...
I just installed The Dark Eye
![image](https://user-images.githubusercontent.com/19734037/235319431-81b005e7-fe46-4bf3-987a-ff9bdf536c35.png)

And it is working for me.

**Comment by bithir** [comment]
https://youtu.be/iCT1-djsGQs

**Comment by bithir** [comment]
Can you validate by just creating an Empty World with The Dark Eye and GM Notes as the only components?

**Comment by bithir** [comment]
@HenrikSonntag

**Comment by HenrikSonntag** [comment]
Sry. I will Test it tomorrow.

________________________________

**Comment by bithir** [comment]
@HenrikSonntag Any luck in testing?

**Comment by HenrikSonntag** [comment]
no, unfortunately it still doesn't work. I once started a game in which I only activated gm notes. it didn't work there. then I updated it and got an error message. In the meantime, the module is no longer displayed in my modules. I get a critical error. pictures are attached
![GM NOtes](https://github.com/bithir/gm-notes/assets/95576279/99677f52-a8ed-4f2a-aec8-92ee50a8bb6c)
![kritischer fehler](https://github.com/bithir/gm-notes/assets/95576279/6d5283b2-5008-4e5f-aa8c-4583b518096b)

**Comment by bithir** [comment]
That looks like the installation is corrupt on your end.  Can you please uninstall GM notes and re-install it?

**Comment by bithir** [comment]
Two choices:
1) Try to re-install GM note (this might resolve your issue without doing things manually)
2) Manually delete the installed module and re-install it

To manually delete it, go to your "User data path" 

![image](https://github.com/bithir/gm-notes/assets/19734037/379406ae-54f6-4f91-8832-ca6757d732cf)
Then in to "Data/modules" and delete the folder called "gm-notes" in there.

**Comment by HenrikSonntag** [comment]
Sorry I didn't reply. it actually works. Thanks for the help

________________________________
